package logic.io.crossbar;
public enum InputSourceD01 {
    LDZ( "Lower Door Zone", 0 ), 
    UDZ( "Upper Door Zone", 1 ), 
    LVCFB( "LVC Feedback", 2 ), 
    LSL( "Lower Shaft Limit", 3 ),
    USL( "Upper Shaft Limit", 4 ), 
    INS( "Inspection", 5 ), 
    INSUP( "Inspection Up", 6 ), 
    INSDOWN( "Inspection Down", 7 ),
    LVC1FB( "LVC1 Feedback", 8 ), 
    DBDE( "Brake Contact", 9 ), 
    DBDF( "Main Contact", 10 ), 
    BS( "Break Switch", 11 ),
    THM( "Thermal Sensor", 12 ), 
    DFC( "Front Door Fully Closed", 13 ), 
    DW( "Front Hall Door Safety Monitor", 14 ), 
    HES( "Hall Safety Monitor", 15 ),
    CES( "Car Safety Monitor", 16 ), 
    DRVBM( "Motor Driver Brake Open", 17 ), 
    DRVOK( "Motor Driver OK", 18 ), 
    RDFC( "Rear Door Fully Closed", 19 ),
    RDW( "Rear Hall Door Safety Monitor", 20 ), 
    ENCF( "Encoder Fail", 21 ), 
    DRVENF( "Motor Driver Enabled Feedback", 22 ),
	LRL("Lower Re-Leveling",23),
	URL("Up Re-Leveling",24),
	DLB("Door Lock-Bypass",25),
	IN_EPB("Emergency Power Operation",26),
	BS1("Break Switch 1",27),
	BS2("Break Switch 2",28),
	NDZ("None Door Zone",29),
	UCMTS1("UCMP Test 1",30),
	UCMTS2("UCMP Test 2",31),
	UCMTS3("UCMP Test 3",32),
	IM("Install Mode",33),
	IU("Install Up",34),
	ID("Install Down",35),
	ISU("Inspect Limit Up",36),
	ISD("Inspect Limit Down",37),
	
    DCS_REDP("DCS REDP",64),
	DCS_EDP("DCS EDP",65),
	DCS_RDOL("DCS RDOL",66),
	DCS_RDCL("DCS RDCL",67),
	DCS_RSGS("DCS RSGS",68),
	DCS_INS("DCS INS",69),
	DCS_DOL("DCS DOL",70),
	DCS_DCL("DCS DCL",71),
	DCS_SGS("DCS SGS",72),
	DCS_NDZ("DCS NDZ",73),
	DCS_INS_UP("DCS INS UP",74),
	DCS_INS_DOWN("DCS INS DOWN",75),
	DCS_CINS("DCS CAR INS",76),
	DCS_CINS_UP("DCS CAR INS UP",77),
	DCS_CINS_DOWN("DCS CAR INS DOWN",78),
	DCS_TSL("DCS TSL",79),
	DCS_FUDZ("DCS FLDZ",80),
	DCS_FLDZ("DCS FUDZ",81),
	DCS_RLDZ("DCS RLDZ",82),
	DCS_RUDZ("DCS RUDZ",83),
	DCS_DRL("DCS DRL",84),
	DCS_URL("DCS URL",85),
	DCS_LSL("DCS LSL",86),
	DCS_USL("DCS USL",87),
	DCS_DOR("DCS DOR",88),
	DCS_DCR("DCS DCR",89),
	DCS_FR("DCS FR",90),
	DCS_LR("DCS LR",91),
	DCS_NDR("DCS NDR",92),
	DCS_RDOR("DCS RDOR",93),
	DCS_RDCR("DCS RDCR",94),
	DCS_RNDR("DCS_RNDR",95),
	DCS_TD1("DCS TD1", 96),
	DCS_TD2("DCS TD2", 97),
	DCS_TD3("DCS TD3", 98),
	DCS_AR("DCS AR", 99),
	
	EPS_RBR("EPS RBR", 100),
	EPS_MCK("EPS MCK", 101),
	EPS_DZI("EPS DZI", 102),
	EPS_ECF("EPS ECF", 103),
	EPS_EBK("EPS EBK", 104),
	
	EPS_IPS("EPS IPS", 110),
	EPS_MBR("EPS MBR", 111),
	EPS_MCR("EPS MCR", 112),
	EPS_XMBR("EPS XMBR", 113),
	EPS_BAT("EPS BAT", 114),
	EPS_RCE("EPS RCE", 115),
	
	CROSS_BAR_END("", 116);

    public final int    configureIndex;
    public final String fullname;

    InputSourceD01 ( String text, int index ) {
        this.fullname       = text;
        this.configureIndex = index;
    }
}
